# Generated by Django 5.0.2 on 2024-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Walker', max_length=50, verbose_name='Drink Name')),
                ('cost', models.IntegerField(default=100)),
                ('opening_stock', models.IntegerField(default=0)),
                ('added_stock', models.IntegerField(default=0)),
                ('sold_stock', models.IntegerField(default=0)),
                ('closing_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
