# Generated by Django 5.1.1 on 2024-10-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_dashboard_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='solddrinks',
            name='status',
            field=models.CharField(default='paid', max_length=10),
        ),
    ]
