# Generated by Django 5.1.1 on 2024-10-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_solddrinks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solddrinks',
            name='customer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
