# Generated by Django 5.1.1 on 2024-10-07 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_solddrinks_options_alter_solddrinks_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('order_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('ending', 'Ending')], max_length=10)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_drinks', to='Home.drinks')),
            ],
        ),
    ]
