# Generated by Django 5.1.1 on 2024-10-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_ordereddrinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereddrinks',
            name='payment_mode',
            field=models.CharField(choices=[('M-pesa', 'M-pesa'), ('Cash', 'Cash')], max_length=50),
        ),
    ]
