# Generated by Django 5.1.1 on 2024-10-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_ordereddrinks_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereddrinks',
            name='order_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=10),
        ),
    ]
