# Generated by Django 5.1.1 on 2024-10-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_ordereddrinks_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereddrinks',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='DateTime Orderd'),
        ),
    ]
