# Generated by Django 5.1.1 on 2024-10-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_ordereddrinks_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereddrinks',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateTime Ordered'),
        ),
    ]
