# Generated by Django 5.1.1 on 2024-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_contact_alter_drinks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Drink Name'),
        ),
    ]
