# Generated by Django 5.1.1 on 2024-10-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(default='Contact/default.png', null=True, upload_to='Contact'),
        ),
    ]
