# Generated by Django 5.1.1 on 2024-11-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_expenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='solddrinks',
            name='payment_mode',
            field=models.CharField(choices=[('Till', 'Till'), ('Cash', 'Cash')], default='Cash', max_length=50),
        ),
    ]
