# Generated by Django 5.1.1 on 2024-11-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_solddrinks_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='wholesale',
            field=models.IntegerField(null=True),
        ),
    ]
