# Generated by Django 5.1.1 on 2024-11-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_drinks_wholesale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solddrinks',
            options={'ordering': ['-date']},
        ),
    ]
