# Generated by Django 5.1.1 on 2024-11-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_alter_solddrinks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solddrinks',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
