# Generated by Django 5.1.1 on 2024-11-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_alter_solddrinks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solddrinks',
            name='payment_mode',
            field=models.CharField(choices=[('Till', 'Till'), ('Cash', 'Cash')], max_length=50, null=True),
        ),
    ]
