# Generated by Django 5.1.1 on 2024-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_alter_solddrinks_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='debt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
