# Generated by Django 5.1.1 on 2024-11-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_dashboard_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solddrinks',
            name='payment_mode',
            field=models.CharField(choices=[('Till', 'Till'), ('Cash', 'Cash'), ('Debt', 'Debt')], max_length=50, null=True),
        ),
    ]
