# Generated by Django 5.0.2 on 2024-08-26 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jkuat Student', max_length=255)),
                ('birthday', models.DateField(default='1990-04-01')),
                ('degree', models.CharField(default='Course', max_length=100)),
                ('experience', models.PositiveIntegerField(default=10)),
                ('phone', models.CharField(default='+012 345 6789', max_length=20)),
                ('email', models.EmailField(default='info@example.com', max_length=254)),
                ('address', models.CharField(default='your address', max_length=255)),
                ('institution', models.CharField(default='JKUAT', max_length=50, null=True)),
                ('picture', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/')),
                ('bio', models.TextField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nemo, dolores, amet possimus ea, hic reiciendis sed porro voluptatem voluptatum architecto inventore! Earum sint repellat, soluta dicta qui quos quasi iure.')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
